### ISSUE TITLE
Bootstrap dependency

### ISSUE THREAD

**Issue by bmwertman** [twinssbc/AngularJS-ResponsiveCalendar#15]
Are their particular components of Bootstrap CSS that are used in this? If I can make a custom build of the Bootstrap CSS file I would like to. I'm having issues with full Bootstrap CSS overwriting styles in my application's CSS.

**Comment by twinssbc** [comment]
@bmwertman I only uses some basic style for the table (not cell, just table container) and the navigation button.
So I think it's probably safe for you to use your own customized CSS.

**Comment by edmondchui** [comment]
@twinssbc Could you please update ```[bower.json](https://github.com/twinssbc/AngularJS-ResponsiveCalendar/blob/master/bower.json)``` to use version 3.3.4 of bootstrap then? The currently specified version ~3.0.3 is too old. Thanks.

**Comment by twinssbc** [comment]
@edmondchui I think it's better to leave the version unchanged, because:
1) when I developed this directive, I referenced boostrap 3.0.3, that means I'm sure it supports bootstrap 3.0.3, but I can't verify the behavior against all bootstrap future versions.
2) If I increase the dependency version in the bower, someone who is still using BS 3.0.3 will be forced to upgrade BS, and it may break the existing page.
3) If your project needs higher version of BS, when you run bower install, it will prompt you to select which version of BS to install

**Comment by edmondchui** [comment]
@twinssbc I see your concerns. Thanks.
