### ISSUE TITLE
Angular Module Loading Issue

### ISSUE THREAD

**Issue by azamsharp** [twinssbc/AngularJS-ResponsiveCalendar#46]
I am getting the following error: 

Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.4.5/$injector/modulerr?p0=GCCICR&p1=Error%3A%…ogleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.4.5%2Fangular.min.js%3A19%3A381)

**Comment by twinssbc** [comment]
@azamsharp This error is a generic error. It usually happens when you failed to inject something, but unfortunately it doesn't print out which one causes the error.
Have you add the dependency of ui.rCalendar like below? Also this error is not certainly because of the calendar, it could be other injected provider, service, directive, etc.

```
var myAppModule = angular.module('MyApp', ['ui.rCalendar'])
```

**Comment by azamsharp** [comment]
Thanks! It was resolved.
